### ISSUE TITLE
API connection error:  net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by whiteb38** [NTag/lyrics.ovh#2]
Looks like your API is having a proxy server error.
Are you still maintaining this?

**Comment by NTag** [comment]
Hello,
I restarted some services. Can you try again? Do you still have the error? For which exact URL?

**Comment by fjoglar** [comment]
Still getting some 502 Proxy Error.

For example with URLs:
- https://api.lyrics.ovh/v1/Lil Nas X/Old Town Road
- https://api.lyrics.ovh/v1Logic/Homicide 
- https://api.lyrics.ovh/v1/benny%20blanco,%20Halsey,%20Khalid/Eastside
- https://api.lyrics.ovh/v1/Taylor%20Swift/ME!%20(feat.%20Brendon%20Urie%20of%20Panic!%20At%20The%20Disco)
- https://api.lyrics.ovh/v1/Post%20Malone/Congratulations%20featuring%20Quavo
