### ISSUE TITLE
Getting some 502 Proxy Error.

### ISSUE THREAD

**Issue by fjoglar** [NTag/lyrics.ovh#5]
Still getting some 502 Proxy Error.

For example with URLs:
- https://api.lyrics.ovh/v1/Lil Nas X/Old Town Road
- https://api.lyrics.ovh/v1Logic/Homicide 
- https://api.lyrics.ovh/v1/benny%20blanco,%20Halsey,%20Khalid/Eastside
- https://api.lyrics.ovh/v1/Taylor%20Swift/ME!%20(feat.%20Brendon%20Urie%20of%20Panic!%20At%20The%20Disco)
- https://api.lyrics.ovh/v1/Post%20Malone/Congratulations%20featuring%20Quavo

_Originally posted by @fjoglar in https://github.com/NTag/lyrics.ovh/issues/2#issuecomment-492407895_

**Comment by thealiilman** [comment]
@fjoglar Not sure if you've used the API ever since you created this issue, but myself just called the API and it's working again! 🎉

**Comment by fjoglar** [comment]
@thealiilman 
Yes it seems to be fixed. Closing the issue.
