### ISSUE TITLE
Issue with fetching lyrics

### ISSUE THREAD

**Issue by Roger-Melo** [NTag/lyrics.ovh#8]
Hi. The API is under maintenance?

![image](https://user-images.githubusercontent.com/29297788/77115538-48fed200-6a0d-11ea-9862-3e99037138b3.png)

**Comment by NTag** [comment]
Small mistake on my side, it should be up quickly. Sorry for the inconvenience!

**Comment by Roger-Melo** [comment]
Nice. I'm enjoying this API a lot =)

**Comment by NTag** [comment]
It's up!

**Comment by Roger-Melo** [comment]
Cooool! Thank you, @NTag =D
